### ISSUE TITLE
Fix for svrl2xvrl?

### ISSUE THREAD

**Issue by xatapult** [xproc/xvrl-tools#1]
I tried the `svrl2xvrl.xsl` and it broke on a rather complex svrl. The following patch resolved this, but I'm not sure I've got it completely right:

```xml
<xsl:template match="svrl:schematron-output" mode="svrl2xvrl">
    <report>
      <metadata>
        <schema schematypens="http://purl.oclc.org/dsdl/schematron"/>
        <xsl:apply-templates select="svrl:active-pattern[1]/@document" mode="#current"/>
      </metadata>
      <xsl:for-each-group select="*" group-starting-with="svrl:active-pattern">
        <xsl:if test="exists(current-group()[1]/self::svrl:active-pattern)">
          <xsl:variable name="pattern" as="element(svrl:active-pattern)" select="."/>
          <xsl:for-each-group select="current-group()[position() gt 1]" group-starting-with="svrl:fired-rule">
            <xsl:apply-templates select="current-group()/(self::svrl:successful-report | self::svrl:failed-assert)" mode="#current">
              <xsl:with-param name="rule" tunnel="yes" as="element(svrl:fired-rule)" select="."/>
              <xsl:with-param name="pattern" tunnel="yes" as="element(svrl:active-pattern)" select="$pattern"/>
            </xsl:apply-templates>
          </xsl:for-each-group>
        </xsl:if>
      </xsl:for-each-group>
    </report>
  </xsl:template>
```

The fix is the added `<xsl:if test="exists(current-group()[1]/self::svrl:active-pattern)">`. If you don't check on this you get groups that don't start with `<svrl:active-pattern>`, which breaks the transformation.

**Comment by gimsieke** [comment]
What do these groups start with? `title` or something? Maybe this would be interesting information for the metadata. I obviously didn’t anticipate anything else there. If you want, you  can apply the change to the XSLT (or file a PR for it).

**Comment by xatapult** [comment]
I got several `<svrl:ns-prefix-in-attribute-values>` elements at the beginning of my SVRL output. 

I'll do some more testing and will apply a fix.

**Comment by xatapult** [comment]
@gimsieke The `<svrl:ns-prefix-in-attribute-values>` elements create a binding between a namespace prefix used in attribute values and a namespace. Is that something that is forgotten in XVRL? 

Sounds kind-a useful...

**Comment by gimsieke** [comment]
I thought XPath expressions will be interpreted as XPath with the `xmlns:…` namespace bindings of the document. 

@mricaud How do you handle this in your XVRL?

**Comment by xatapult** [comment]
For the XPath expression as output by SVRL, the namespace prefixes are not necessarily bound by `xmlns:...="..."` expressions.

**Comment by gimsieke** [comment]
Maybe we can transform `svrl:ns-prefix-in-attribute-values` elements to namespace declarations.

**Comment by mricaud** [comment]
@gimsieke sorry for this late reply 

> @mricaud How do you handle this in your XVRL?

 I actually didn't handle it at all, my use case was with an empty namespace by default. But yes, it's really usefull to have this an equivalent for <svrl:ns-prefix-in-attribute-values>. And I agree with @xatapult with a simple namespace declaration.
